
"use client";

import { LayoutTemplate, Target, Megaphone, BarChart3, Users, Zap } from "lucide-react";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

export default function CreatorPage() {
  return (
    <div className="container mx-auto px-4 py-12 max-w-6xl">
      <div className="mb-12">
        <h1 className="text-3xl font-bold mb-2">Club Creator Hub</h1>
        <p className="text-muted-foreground">AI-powered tools to grow your community with transparency and trust.</p>
      </div>

      <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-8">
        {[
          { icon: Megaphone, title: "Smart Campaigns", desc: "Generate transparent event descriptions that explain why members should join." },
          { icon: Target, title: "Audience Insights", desc: "Understand your community's budget and accessibility needs without compromising privacy." },
          { icon: Zap, title: "Diversity Booster", desc: "Find underserved student groups to invite to your next event." },
          { icon: BarChart3, title: "Impact Tracking", desc: "Measure member trust and engagement over time." },
          { icon: Users, title: "Collaboration", desc: "Partner with other clubs using shared resource planning." },
          { icon: LayoutTemplate, title: "Templates", desc: "Professional club branding and assets generated by explainable AI." }
        ].map((tool, i) => (
          <Card key={i} className="hover:shadow-md transition-shadow">
            <CardHeader>
              <tool.icon className="h-8 w-8 text-primary mb-2" />
              <CardTitle className="text-lg">{tool.title}</CardTitle>
              <CardDescription>{tool.desc}</CardDescription>
            </CardHeader>
            <CardContent>
              <Button variant="outline" className="w-full">Open Tool</Button>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}
